// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamHolidayCalendarBackend.Data;

#nullable disable

namespace TeamHolidayCalendarBackend.Migrations
{
    [DbContext(typeof(LeavePlanDbContext))]
    partial class LeavePlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamHolidayCalendarBackend.Models.LeavePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaveStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeavePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b648d1d-32ae-48cb-ab0d-2bd79eea181c"),
                            EmployeeName = "Aslam",
                            LeaveEndDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveReason = "Sick",
                            LeaveStartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5b6203c8-8b3d-4717-b268-037f66e01ec6"),
                            EmployeeName = "Babar",
                            LeaveEndDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveReason = "Urgent Work",
                            LeaveStartDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2d84115-ea51-4aaa-be40-09a45e5998d3"),
                            EmployeeName = "Jameel",
                            LeaveEndDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveReason = "Brother Marriage",
                            LeaveStartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b7326f91-c5b3-434a-8011-29d5cee626ee"),
                            EmployeeName = "Azeem",
                            LeaveEndDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveReason = "Doctor Appointment",
                            LeaveStartDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("584d8d8c-e832-4366-abb4-957bea83fdfe"),
                            EmployeeName = "Rizwan",
                            LeaveEndDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveStartDate = new DateTime(2024, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("70579101-c445-4af5-9e94-57287c214b90"),
                            EmployeeName = "Iftikhar",
                            LeaveEndDate = new DateTime(2024, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveStartDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
